# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[en]
 languageCode = "en"
 contentDir = "content/en"
 title = "Academic"
#  [en.params]
#    description = "Tech Mansion"
#  [[en.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
