[zh]
  languageCode = "zh"
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir = "content/zh"

# Uncomment for multilingual sites, and customize the following config.
[en]
  languageCode = "en"
  contentDir = "content/en"
  title = "中文标题"